name = "Eyeversuseye"
license = "MIT"
licenselink = "https://github.com/yratof/evehugo/blob/master/LICENSE.md"
description = "The theme that EVE built"
homepage = "http://eyeversuseye.com/hugo"
tags = []
features = []
min_version = "0.31.1"

[author]
  name = "Andrew Lazarus"
  homepage = "http://eyeversuseye.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
